In [3]:
import pandas as pd

# Load the dataset
df = pd.read_csv("ecommerce_return_augmented.csv")

# === HANDLE MISSING VALUES ===
df['Return_Date'] = df['Return_Date'].fillna('Not Returned')
df['Return_Reason'] = df['Return_Reason'].fillna('No Return')
df['Days_to_Return'] = df['Days_to_Return'].fillna(0)
df['Region'] = df['Region'].fillna(df['Region'].mode()[0])

# === CONVERT DATE COLUMNS ===
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')
df['Return_Date'] = pd.to_datetime(df['Return_Date'], errors='coerce')

# === CONVERT BOOLEAN COLUMNS TO INTEGER ===
df['Product_Returnable'] = df['Product_Returnable'].astype(int)
df['High_Return_Risk_Flag'] = df['High_Return_Risk_Flag'].astype(int)

# === EXTRACT DATE FEATURES ===
df['Order_Weekday'] = df['Order_Date'].dt.day_name()  # Gives 'Monday', 'Tuesday', etc.
df['Order_Month'] = df['Order_Date'].dt.month

# Preview processed data
df.head()

,Order_ID,Product_ID,User_ID,Order_Date,Return_Date,Product_Category,Product_Price,Order_Quantity,Return_Reason,Return_Status,...,Payment_Method,Shipping_Method,Discount_Applied,Region,Marketing_Channel,Customer_Tenure_Months,Product_Returnable,High_Return_Risk_Flag,Order_Weekday,Order_Month
0,ORD00000000,PROD00000000,USER00000000,2023-08-05,2024-08-26,Clothing,411.59,3,Changed mind,Returned,...,Debit Card,Next-Day,45.27,East,Referral,57,1,1,Saturday,8
1,ORD00000001,PROD00000001,USER00000001,2023-10-09,2023-11-09,Books,288.88,3,Wrong item,Returned,...,Credit Card,Express,47.79,North,Email,29,0,0,Monday,10
2,ORD00000002,PROD00000002,USER00000002,2023-05-06,NaT,Toys,390.03,5,No Return,Not Returned,...,Debit Card,Next-Day,26.64,East,Referral,25,0,0,Saturday,5
3,ORD00000003,PROD00000003,USER00000003,2024-08-29,NaT,Toys,401.09,3,No Return,Not Returned,...,PayPal,Next-Day,15.37,East,Social Media,21,0,0,Thursday,8
4,ORD00000004,PROD00000004,USER00000004,2023-01-16,NaT,Books,110.09,4,No Return,Not Returned,...,Gift Card,Standard,16.37,Central,Email,46,0,0,Monday,1

In [5]:
df.to_csv("ecommerce_return_cleaned.csv", index=False)

In [7]:
output_path = r"C:\Users\ushas\OneDrive\Desktop\ecommerce_return_cleaned.csv"
df.to_csv(output_path, index=False)
print("Cleaned file saved to Desktop!")

Cleaned file saved to Desktop!